Ice Block Dispenser
solent-group/StudioModule2024 pull request #84
Opened 2024-02-27 15:19 UTC by odinx311

Empty controls location of the Ice Cube spawner, there is a Sphere as a button with a button script, where you are able to change the amount of ice cubes you would like to spawn, if you click timed button, you can set a timer of when they spawn, if set to 2 for example, every 2 seconds it would spawn a "ice block cube"

2024-02-27 19:26 UTC, domibron submitted a review, later dismissed
Not up to GDD specs.
Should keep tack of the spawned items and have a max amount.
If a cube is destroyed this count should go down so it can spawn the cube.

2024-02-29 18:46 UTC, odinx311 commented
Can't figure out how to keep track of destroyed cubes, attempted to gradually rotate the pipe open but could only get it to snap open instantly. 
(implemented in new pull request)

2024-02-29 19:28 UTC, BananaBros2 requested changes
Don't need code to rotate the chute, objects spit out by the dispenser need to be tracked so that when they disappear a new one can spawn. Doesn't seem to have required customisation, check GDD for other notable changes.
https://docs.google.com/document/d/1z1LMCl1OOUa6hZlI-PeDRbTQNl6nrGLFXl54sEH095o/edit#heading=h.34qd47mwmliq

2024-03-05 19:40 UTC, BananaBros2 approved these changes

2024-03-05 19:43 UTC, merged